#!/bin/bash
if systemctl is-active --quiet solana-validator.service; then
    sudo systemctl stop solana-validator.service
    sudo systemctl daemon-reload
fi
sudo systemctl start solana-validator.service
echo "Solana Validator reloaded and started."